### ISSUE TITLE
Packages Upgrade

### ISSUE THREAD

**Issue by soufiane-bouchaara** [capsule-corp-ternoa/explorer#39]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/2540416/185204888-0037c388-e376-4ea7-a10f-e93e96bd4cd1.png">

**Comment by ipapandinas** [comment]
Solved in this commit: https://github.com/capsule-corp-ternoa/explorer/commit/a7037db6e6665d6d6c6e2078bda4a9de6b602bcc
